version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: pdv-erp-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pdv_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: pdv-erp-server
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pdv_db
    depends_on:
      - db

volumes:
  postgres_data:
